/*
(Partially) Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/plantb.glb -t 

Blendkit Model:
  author: Matteo Pascale (https://www.blendkit.com/?query=author_id:17876)
  license: Royalty Free
  source: https://www.blendkit.com/asset-gallery-detail/a5b84e00-8661-4b76-879d-00b7bcad1450/
  title: Moduler Fiscus Plant
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";
import { useEffect, useRef } from 'react';

import type { LeafStates } from '../api/useReadings';
export type MaterialKey = 'stem'

const modelUrl = `${import.meta.env.BASE_URL}plantb.glb`;

const idToLeafMatMap: Record<string, MaterialKey> = {
    "0": 'stem',
}

type GLTFResult = GLTF & {
  nodes: {
    Leaves: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder001_1: THREE.Mesh
    Cylinder001_2: THREE.Mesh
    Stem: THREE.Mesh
  }
  materials: {
    leaves: THREE.MeshBasicMaterial
    ['Glazed ceramic']: THREE.MeshBasicMaterial
    Plastic: THREE.MeshStandardMaterial
    ['Procedural Dirt']: THREE.MeshStandardMaterial
    stem: THREE.MeshBasicMaterial
  }
}

interface Props {
  leafStates: LeafStates;
}
const leaf_active_color = new THREE.Color().lerpColors(
  new THREE.Color(0x433A08),
  new THREE.Color(0x69BFB6), 
  0.2
);

const dirtColor = new THREE.MeshBasicMaterial({ color: 0x120606});

export function Plant({leafStates} : Props) {
  const { nodes, materials } = useGLTF(modelUrl) as unknown as GLTFResult
  const materials_cache = useRef<Record<MaterialKey, { map: THREE.Texture | null; color: THREE.Color }>>({ stem: { map: null, color: new THREE.Color() } as any });

  const resetMatTimeout = useRef<Record<MaterialKey, ReturnType<typeof setTimeout>>>({ stem: undefined as any });
  useEffect(() => {
    Object.entries(idToLeafMatMap).forEach(([, matId]) => {
      const mat = materials[matId] as THREE.MeshBasicMaterial;
      materials_cache.current[matId] = {
        map: mat.map,
        color: mat.color.clone()
      };
    });
  }, []);

  useEffect(() => {
    if (leafStates == null) return;
    Object.entries(leafStates).forEach(([leafId, state]) => {
      if (!(leafId in idToLeafMatMap)) return
      const matId = idToLeafMatMap[leafId] as MaterialKey

      const mat = materials[matId] as THREE.MeshBasicMaterial;

      if (state) {
        mat.map = null;
        mat.color.copy(leaf_active_color);
        mat.needsUpdate = true;
      } else {
        if (resetMatTimeout.current[matId]) {
          clearTimeout(resetMatTimeout.current[matId]);
        }
        resetMatTimeout.current[matId] = setTimeout(() => {
          const cachedMat = materials_cache.current[matId];
          console.log(mat);
          if (cachedMat) {
            mat.map = cachedMat.map;
            mat.color.copy(cachedMat.color);
            mat.needsUpdate = true;
          }
        }, 1500)
      }
      
    })
  }, [leafStates, materials]);

  return (
    <Canvas className="cursor-grab w-full h-full" camera={{ position: [-5, 1, 0]}}>
        <ambientLight intensity={0.5} />
        <OrbitControls
            enableZoom={false}
            enablePan={false}
            target={[0, 1, 0]}
            maxDistance={2.5}
        />
        <group dispose={null} scale={3} position={[0, -0.3, 0]} rotation={[0, 36, 0]}>
          <mesh geometry={nodes.Leaves.geometry} material={materials.leaves} />
          <mesh geometry={nodes.Stem.geometry} material={materials.stem} />
          <mesh geometry={nodes.Cylinder001.geometry} material={materials['Glazed ceramic']} />
          <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.Plastic} />
          <mesh geometry={nodes.Cylinder001_2.geometry} material={dirtColor} />
        </group>
    </Canvas>
  )
}

export default Plant;

useGLTF.preload(modelUrl)