/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/plant.gltf -t 

====== Sketchfab Model =============================================================================

  author: assetfactory (https://sketchfab.com/assetfactory)
  license: Free Standard
  source: https://sketchfab.com/3d-models/house-palm-plant-346a62f326824803bec27dc53703396a
  title: House palm plant

===================================================================================================
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";
import { useEffect } from 'react';

type GLTFResult = GLTF & {
  nodes: {
    Pot_1: THREE.Mesh
    Pot_2: THREE.Mesh
    Leaf3: THREE.Mesh
    Leaf4: THREE.Mesh
    Leaf1: THREE.Mesh
    Leaf2: THREE.Mesh
  }
  materials: {
    FlowerPot: THREE.MeshStandardMaterial
    Soil: THREE.MeshStandardMaterial
    leaf3: THREE.MeshStandardMaterial
    leaf4: THREE.MeshStandardMaterial
    leaf1: THREE.MeshStandardMaterial
    leaf2: THREE.MeshStandardMaterial
  }
}


const POS = {x: 0, y: -0.1, z: 0}

export function Plant() {
  const { nodes, materials } = useGLTF('/plant.gltf') as unknown as GLTFResult


  return (
    <Canvas className="cursor-grab" camera={{ position: [-5, 3, 0]}}>
        <ambientLight intensity={0.5} />
        <directionalLight position={[0, 10, 0]} intensity={2} />
        <OrbitControls
            enableZoom={false}
            enablePan={false}
            target={[0, 1, 0]}
            maxDistance={2.5}
        />

        <group dispose={null}>
            <mesh geometry={nodes.Leaf3.geometry} material={materials.leaf3} position={[0.095+POS.x, 0.799+POS.y, -0.127+POS.z]} rotation={[0, -0.49, 0]} />
            <mesh geometry={nodes.Leaf2.geometry} material={materials.leaf2} position={[-0.094+POS.x, 0.696+POS.y, -0.127+POS.z]} rotation={[0, 0.522, 0]} scale={0.774} />
            <mesh geometry={nodes.Leaf4.geometry} material={materials.leaf4} position={[0.077+POS.x, 0.799+POS.y, 0.069+POS.z]} rotation={[Math.PI, -1.098, Math.PI]} />
            <mesh geometry={nodes.Leaf1.geometry} material={materials.leaf1} position={[0.057+POS.x, 0.651+POS.y, 0.029+POS.z]} rotation={[-Math.PI, 1.198, -Math.PI]} />
            <group position={[-0.025+POS.x, 0.226+POS.y, 0+POS.z]} scale={0.424}>
                <mesh geometry={nodes.Pot_1.geometry} material={materials.FlowerPot} />
                <mesh geometry={nodes.Pot_2.geometry} material={materials.Soil} />
            </group>
        
        </group>
    </Canvas>
  )
}

export default Plant;

useGLTF.preload('/plant.gltf')