/*
(Partially) Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/plant.gltf -t 

====== Sketchfab Model =============================================================================

  author: assetfactory (https://sketchfab.com/assetfactory)
  license: Free Standard
  source: https://sketchfab.com/3d-models/house-palm-plant-346a62f326824803bec27dc53703396a
  title: House palm plant

===================================================================================================
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";
import { useEffect, useRef } from 'react';

import type { LeafStates } from '../api/useReadings';
export type MaterialKey = 'stem1' | 'stem2' | 'stem3' | 'stem4'

const modelUrl = `${import.meta.env.BASE_URL}plantb.glb`;

const idToLeafMatMap: Record<string, MaterialKey> = {
    "0": 'stem1',
    "1": 'stem2',
    "2": 'stem3',
    "3": 'stem4'
}

type GLTFResult = GLTF & {
  nodes: {
    Leaf1: THREE.Mesh
    Leaf2: THREE.Mesh
    Leaf3: THREE.Mesh
    Leaf4: THREE.Mesh
    Pot: THREE.Mesh
    Pot_1: THREE.Mesh
    Pot_2: THREE.Mesh
  }
  materials: {
    stem1: THREE.MeshStandardMaterial
    stem4: THREE.MeshStandardMaterial
    stem3: THREE.MeshStandardMaterial
    stem2: THREE.MeshStandardMaterial
    FlowerPot: THREE.MeshStandardMaterial
    Soil: THREE.MeshStandardMaterial
    ['All Leaves']: THREE.MeshStandardMaterial
  }
}


const POS = {x: 0, y: -0.1, z: 0}

interface Props {
  leafStates: LeafStates;
}
const leaf_inactive_color = new THREE.Color().lerpColors(
  new THREE.Color('#4AC74C'),
  new THREE.Color('#99D9FF'), 
  0
);
const leaf_active_color = new THREE.Color().lerpColors(
  new THREE.Color('#4AC74C'),
  new THREE.Color('#99D9FF'), 
  5
);

export function Plant({leafStates} : Props) {
  const { nodes, materials } = useGLTF(modelUrl) as unknown as GLTFResult

  const resetMatTimeout = useRef<Record<MaterialKey, ReturnType<typeof setTimeout>>>({ stem1: undefined as any, stem2: undefined as any, stem3: undefined as any, stem4: undefined as any });
  
  useEffect(() => {
    const mat = materials['All Leaves'] as THREE.MeshStandardMaterial;
    mat.color.copy(leaf_inactive_color);
  }, [])

  useEffect(() => {
    if (leafStates == null) return;
    Object.entries(leafStates).forEach(([leafId, state]) => {
      if (!(leafId in idToLeafMatMap)) return
      const matId = idToLeafMatMap[leafId] as MaterialKey

      const mat = materials[matId] as THREE.MeshStandardMaterial;
      
      if (state) {
        mat.color.copy(leaf_active_color);
      } else {
        if (resetMatTimeout.current[matId]) {
          clearTimeout(resetMatTimeout.current[matId]);
        }
        resetMatTimeout.current[matId] = setTimeout(() => {
          mat.color.copy(leaf_inactive_color);
        }, 1000)
      }
      
    })
  }, [leafStates]);

  return (
    <Canvas className="cursor-grab w-full h-full" camera={{ position: [-5, 3, 0]}}>
        <ambientLight intensity={0.5} />
        <directionalLight position={[0, 10, 0]} intensity={2} />
        <OrbitControls
            enableZoom={false}
            enablePan={false}
            target={[0, 1, 0]}
            maxDistance={2.5}
        />

        <group dispose={null}>
          <mesh geometry={nodes.Leaf1.geometry} material={materials.stem1} position={[-0.025, 0.13, 0]} scale={0.424} />
          <mesh geometry={nodes.Leaf2.geometry} material={materials.stem4} position={[-0.025, 0.13, 0]} scale={0.424} />
          <mesh geometry={nodes.Leaf3.geometry} material={materials.stem3} position={[-0.025, 0.13, 0]} scale={0.424} />
          <mesh geometry={nodes.Leaf4.geometry} material={materials.stem2} position={[-0.025, 0.13, 0]} scale={0.424} />
          <group position={[-0.025+POS.x, 0.226+POS.y, 0+POS.z]} scale={0.424}>
            <mesh geometry={nodes.Pot.geometry} material={materials.FlowerPot} />
            <mesh geometry={nodes.Pot_1.geometry} material={materials.Soil} />
            <mesh geometry={nodes.Pot_2.geometry} material={materials['All Leaves']} />
          </group>
        </group>
    </Canvas>
  )
}

export default Plant;

useGLTF.preload(modelUrl)