# Generated by Django 6.0.7 on 2026-07-21 21:38

from django.db import migrations

DEFAULT_CONFIG = {
    "FireMode": "false",
}

def seed_config(apps, schema_editor):
    Configs = apps.get_model('telemetry', 'Configs')
    for key, value in DEFAULT_CONFIG.items():
        Configs.objects.get_or_create(key=key, defaults={"value": value})
        

def unseed_config(apps, schema_editor):
    Configs = apps.get_model('telemetry', 'Configs')
    Configs.objects.filter(key__in=DEFAULT_CONFIG.keys()).delete()
        
class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_config, reverse_code=unseed_config),
    ]
