/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/plantb.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Leaves: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder001_1: THREE.Mesh
    Cylinder001_2: THREE.Mesh
    Stem: THREE.Mesh
  }
  materials: {
    leaves: THREE.MeshBasicMaterial
    ['Glazed ceramic']: THREE.MeshBasicMaterial
    Plastic: THREE.MeshStandardMaterial
    ['Procedural Dirt']: THREE.MeshStandardMaterial
    stem: THREE.MeshBasicMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/plantb.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Leaves.geometry} material={materials.leaves} />
      <mesh geometry={nodes.Stem.geometry} material={materials.stem} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Glazed ceramic']} />
      <mesh geometry={nodes.Cylinder001_1.geometry} material={materials.Plastic} />
      <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Procedural Dirt']} />
    </group>
  )
}

useGLTF.preload('/plantb.glb')
